- name: nginx rpm update
  yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm

- name: nginx install
  yum: name=nginx state=latest

- name: docroot mkdir
  file: dest=/var/www group=vagrant owner=vagrant recurse=yes

- name: default nginx conf backup
  shell: mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bak

- name: nginx conf
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/nginx.conf owner=nginx group=nginx

- name: start nginx
  service: name=nginx state=started enabled=yes
