- name: mysql rpm install
  yum:
    name: http://dev.mysql.com/get/mysql57-community-release-el6-7.noarch.rpm
    state: present

- name: mysql install
  yum: 
    name: "{{ item }}"
    enablerepo:  mysql56-community
    disablerepo: mysql57-community
    state: present
  with_items: "{{ mysql_packages }}"

- name: mysqld ruuning and enabled
  service:
    name=mysqld
    state=started
    enabled=yes
  tags: mysqld
  become: yes
