- name: composer install
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin
- name: move composer.phar to composer
  command: mv /usr/bin/composer.phar /usr/bin/composer
- name: laravel install global
  shell: composer global require "laravel/installer=~1.1"
