- name: install php
  yum: name=php state=present enablerepo=remi-php56

- name: install php package
  yum: name={{ item }} state=present enablerepo=remi,remi-php56
  with_items: php_packages

- name: php-fpm conf apache to nginx replace
  replace: dest=/etc/php-fpm.d/www.conf regexp='apache' replace='nginx' backup=yes

- name: start php-fpm
  service: name=php-fpm state=started enabled=yes
